name: dotnet_ci

on:
  push:
    branches: [ "part_2" ]
  pull_request:
    branches: [ "part_2" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}    
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build
  
      # Execute all tests in the solution
      - name: Execute tests
        run: dotnet test
      
       
